# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:maledictus",
    "cataclysm:coral_golem",
    "boh:neco_arc",
    "theabyss:laro_fish",
    "born_in_chaos_v1:siamese_skeletonsleft",
    "born_in_chaos_v1:siamese_skeletonsright",
    "minecraft:trader_llama",
    "bwrtherain:vapor",
    "goblintraders:goblin_trader",
    "minecraft:horse",
    "the_knocker:knockerdeadanimal",
    "born_in_chaos_v1:lifestealer",
    "boh:whiteface",
    "scguns:hive",
    "born_in_chaos_v1:riding_felsteed",
    "born_in_chaos_v1:pumpkin_bomb",
    "minecraft:llama",
    "born_in_chaos_v1:skeleton_demoman",
    "theabyss:guard",
    "graveyard:skeleton_creeper",
    "boh:facehugger",
    "cataclysm:ender_guardian",
    "cataclysm:deepling_warlock",
    "minecraft:tadpole",
    "minecraft:dolphin",
    "born_in_chaos_v1:supreme_bonescaller",
    "knock_knock:trailerdummy",
    "boh:herobrine",
    "theabyss:ralu_fish",
    "boh:ao_oni",
    "graveyard:nightmare",
    "theabyss:luro_fish",
    "boh:gold_hostile",
    "fennecfox:fennecfox",
    "boh:demogorgon",
    "boh:sonic_exe",
    "bwrtherain:valem",
    "minecraft:bee",
    "graveyard:reaper",
    "minecraft:illusioner",
    "goblintraders:vein_goblin_trader",
    "born_in_chaos_v1:dread_hound",
    "born_in_chaos_v1:skeleton_thrasher_not_despawn",
    "bwrtherain:spider_skull",
    "minecraft:mooshroom",
    "stalwart_dungeons:nether_wart_cocoon",
    "born_in_chaos_v1:seared_spirit_not_despawn",
    "minecraft:drowned",
    "born_in_chaos_v1:bone_imp_minion",
    "minecraft:axolotl",
    "theabyss:powered_wolf",
    "stalwart_dungeons:nether_keeper",
    "born_in_chaos_v1:senor_pumpkin",
    "zombies_plus:crawler_zombie",
    "knock_knock:hiding",
    "theabyss:hummingbird",
    "minecraft:wandering_trader",
    "boh:eyeless_jack",
    "born_in_chaos_v1:glutton_fish",
    "deeperdarker:angler_fish",
    "born_in_chaos_v1:corpse_fish",
    "born_in_chaos_v1:supreme_bonescaller_stage_2",
    "zombies_plus:leaper_zombie",
    "scguns:zombified_hornlin",
    "theabyss:abyssal_lion",
    "scguns:blunderer",
    "theabyss:brain_walker",
    "cataclysm:netherite_monstrosity",
    "theabyss:jungle_lurker",
    "knock_knock:node",
    "cataclysm:wadjet",
    "hordes:drowned_player",
    "boh:james_sunderland",
    "boh:michael_davies",
    "graveyard:wraith",
    "minecraft:pufferfish",
    "born_in_chaos_v1:bone_imp",
    "boh:taken_pillar",
    "boh:big_daddy",
    "minecraft:fox",
    "born_in_chaos_v1:nightmare_stalker",
    "born_in_chaos_v1:firelight",
    "zombies_plus:bow_zombie",
    "cataclysm:koboleton",
    "call_of_yucutan:ahaw",
    "boh:fresno_nightwalker",
    "minecraft:chicken",
    "born_in_chaos_v1:mr_pumpkin_controlled",
    "minecraft:zombie",
    "theabyss:infected_zombie",
    "theabyss:infceted_cow",
    "graveyard:acolyte",
    "theabyss:frost_spider",
    "theabyss:the_roka",
    "born_in_chaos_v1:siamese_skeletons",
    "born_in_chaos_v1:lord_pumpkinhead",
    "scguns:swarm",
    "born_in_chaos_v1:zombie_lumberjack",
    "vampirism:converted_creature",
    "vampirism:converted_fox",
    "cataclysm:elite_draugr",
    "minecraft:hoglin",
    "the_silence:the_cosa",
    "born_in_chaos_v1:lords_felsteed",
    "the_knocker:knockerstalklooked",
    "theabyss:lokus",
    "cataclysm:deepling_angler",
    "boh:little_sister",
    "hordes:husk_player",
    "cataclysm:draugr",
    "boh:wendigo",
    "minecraft:polar_bear",
    "theabyss:mud_zombie",
    "stalwart_dungeons:incomplete_wither",
    "minecraft:zombified_piglin",
    "minecraft:turtle",
    "minecraft:sheep",
    "knock_knock:trailerdummy_2",
    "born_in_chaos_v1:lord_pumpkinhead_head",
    "boh:red",
    "boh:slender_man",
    "graveyard:ghoul",
    "born_in_chaos_v1:zombie_fisherman",
    "born_in_chaos_v1:lord_pumpkinhead_withouta_horse",
    "born_in_chaos_v1:controlled_baby_skeleton",
    "born_in_chaos_v1:fallen_chaos_knight",
    "deeperdarker:sculk_leech",
    "minecraft:ravager",
    "theabyss:infected_dragonfly",
    "boh:sotiris",
    "theabyss:lizard",
    "boh:simonhenriksson",
    "boh:entity_well",
    "theabyss:abylager",
    "vampirism:converted_horse",
    "born_in_chaos_v1:door_knight_not_despawn",
    "deeperdarker:sludge",
    "bakery:wandering_baker",
    "born_in_chaos_v1:spirit_guide",
    "boh:xenomorph",
    "theabyss:nightblade_boss",
    "stalwart_dungeons:giddy_blaze",
    "born_in_chaos_v1:dread_hound_not_despawn",
    "theabyss:soul_guard",
    "born_in_chaos_v1:riding_lords_felsteed",
    "boh:chestburster",
    "call_of_yucutan:updater",
    "born_in_chaos_v1:zombie_clown_not_despawn",
    "zombies_plus:cave_zombie",
    "cataclysm:ender_golem",
    "boh:jason_voorhees",
    "stalwart_dungeons:reinforced_blaze",
    "boh:decoy_dog",
    "boh:mothman",
    "theabyss:raptor",
    "theabyss:infected_phantom",
    "born_in_chaos_v1:spiritof_chaos",
    "theabyss:magician",
    "born_in_chaos_v1:sir_pumpkinhead",
    "theabyss:infected_spider",
    "minecraft:bat",
    "theabyss:player_body",
    "born_in_chaos_v1:bloody_gadfly",
    "theabyss:night_blade_boss_clone",
    "bwrtherain:rosemary",
    "born_in_chaos_v1:skeleton_thrasher",
    "born_in_chaos_v1:decrepit_skeleton",
    "vampirism:converted_goat",
    "boh:gold_lost",
    "born_in_chaos_v1:controlled_spiritual_assistant",
    "boh:six",
    "theabyss:deer",
    "boh:book_simon",
    "fromtheshadows:froglin",
    "theabyss:infected_creeper",
    "born_in_chaos_v1:bonescaller_not_despawn",
    "the_knocker:knocker",
    "born_in_chaos_v1:baby_skeleton",
    "born_in_chaos_v1:lifestealer_true_form",
    "cataclysm:deepling",
    "fromtheshadows:nehemoth",
    "born_in_chaos_v1:thornshell_crab",
    "cataclysm:ancient_remnant",
    "scguns:dissident",
    "minecraft:cat",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "zombies_plus:slow_zombie",
    "minecraft:panda",
    "minecraft:zombie_villager",
    "theabyss:summoned_hollow_seeker",
    "born_in_chaos_v1:dire_hound_leader",
    "stalwart_dungeons:propulk",
    "minecraft:giant",
    "boh:stiltwalker",
    "boh:ben_drowned",
    "the_silence:asucwacho",
    "scguns:cog_knight",
    "theabyss:jelly_fish",
    "cataclysm:amethyst_crab",
    "born_in_chaos_v1:maggot",
    "stalwart_dungeons:shelterer",
    "theabyss:slime_spider",
    "hordes:zombie_player",
    "cataclysm:ancient_ancient_remnant",
    "minecraft:husk",
    "theabyss:seeker",
    "born_in_chaos_v1:firelight_not_despawn",
    "boh:rexy",
    "born_in_chaos_v1:door_knight",
    "stalwart_dungeons:spore_projectile",
    "scguns:hornlin",
    "theabyss:infected_wolf",
    "call_of_yucutan:golden_guard",
    "knock_knock:rehiding",
    "deeperdarker:sculk_centipede",
    "minecraft:donkey",
    "born_in_chaos_v1:felsteed",
    "born_in_chaos_v1:spirit_guide_assistant",
    "born_in_chaos_v1:baby_skeleton_minion",
    "cataclysm:ignited_berserker",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "boh:taken_hands",
    "boh:souichi",
    "theabyss:crystal_golem",
    "cataclysm:the_baby_leviathan",
    "boh:exe_monitor",
    "deeperdarker:stalker",
    "boh:goji",
    "cataclysm:deepling_brute",
    "theabyss:hylia_fox",
    "theabyss:glow_pug",
    "born_in_chaos_v1:pumpkin_spirit",
    "theabyss:end_spider",
    "the_silence:the_silence_door",
    "born_in_chaos_v1:mr_pumpkin",
    "boh:specimen_9_boss",
    "vampirism:converted_sheep",
    "graveyard:nameless_hanged",
    "boh:siren_head",
    "boh:rat",
    "born_in_chaos_v1:infernal_spirit",
    "born_in_chaos_v1:phantom_creeper",
    "born_in_chaos_v1:sir_pumpkinhead_without_horse",
    "call_of_yucutan:mitnal_monkey",
    "minecraft:parrot",
    "the_silence:la_cosa_real",
    "scguns:redcoat",
    "call_of_yucutan:kukulkan",
    "boh:seed_eater",
    "zombies_plus:vile_zombie",
    "boh:saucer",
    "cataclysm:the_watcher",
    "call_of_yucutan:undead_warrior",
    "vinery:mule",
    "stalwart_dungeons:shelterer_without_armor",
    "minecraft:frog",
    "zombies_plus:brute_zombie",
    "the_silence:cosa_screamer",
    "boh:rake",
    "minecraft:mule",
    "vampirism:converted_cow",
    "vampirism:hunter_minion",
    "vinery:wandering_winemaker",
    "zombies_plus:shrieker_zombie",
    "minecraft:vindicator",
    "theabyss:ice_knight",
    "call_of_yucutan:chaac",
    "minecraft:evoker",
    "born_in_chaos_v1:barrel_zombie",
    "scguns:supply_scamp",
    "theabyss:shattered_zombie",
    "cataclysm:nameless_sorcerer",
    "fromtheshadows:cleric",
    "cataclysm:endermaptera",
    "graveyard:ghouling",
    "the_silence:the_silence_screamer",
    "vampirism:villager_angry",
    "vampirism:blinding_bat",
    "cataclysm:lionfish",
    "born_in_chaos_v1:decaying_zombie",
    "born_in_chaos_v1:corpse_fly",
    "cataclysm:coralssus",
    "the_silence:nothing_playing",
    "graveyard:revenant",
    "graveyard:lich",
    "knock_knock:looking",
    "graveyard:corrupted_pillager",
    "boh:real_deer",
    "boh:whiteface_friendly",
    "the_silence:the_silence_sleep",
    "cataclysm:the_harbinger",
    "vampirism:vampire_minion",
    "the_silence:the_cosa_2",
    "theabyss:scorpion",
    "born_in_chaos_v1:phantom_bomb_entity",
    "boh:krampus",
    "boh:lifeform",
    "the_knocker:knockerstalk",
    "minecraft:pig",
    "born_in_chaos_v1:restless_spirit",
    "boh:raatma",
    "born_in_chaos_v1:swarmer",
    "vampirism:converted_creature_imob",
    "minecraft:goat",
    "boh:springtrap",
    "minecraft:cod",
    "theabyss:haunted_skeleton",
    "boh:smile_dog",
    "vampirism:converted_donkey",
    "born_in_chaos_v1:pumpkinhead",
    "scguns:cog_minion",
    "theabyss:abyssaur",
    "knock_knock:angry_2",
    "boh:ratazana",
    "minecraft:cow",
    "born_in_chaos_v1:scarlet_persecutor",
    "born_in_chaos_v1:phantom_creeper_copy",
    "boh:pyramid_head",
    "boh:granny",
    "minecraft:salmon",
    "cataclysm:ignis",
    "born_in_chaos_v1:seared_spirit",
    "zombies_plus:crossbow_zombie",
    "born_in_chaos_v1:dark_vortex",
    "boh:unown_8",
    "boh:unown_7",
    "boh:unown_6",
    "boh:michael_myers",
    "boh:unown_5",
    "theabyss:versa_whale",
    "boh:jeff_the_killer",
    "boh:unown_4",
    "zombies_plus:axe_zombie",
    "boh:unown_3",
    "zombies_plus:runner_zombie",
    "boh:unown_2",
    "boh:unown_1",
    "knock_knock:angry",
    "the_silence:the_silence_principal",
    "born_in_chaos_v1:zombie_clown",
    "minecraft:rabbit",
    "boh:unown_9",
    "minecraft:pillager",
    "boh:saw_runner",
    "born_in_chaos_v1:decaying_zombie_not_despawn",
    "boh:nemesis",
    "minecraft:zoglin",
    "born_in_chaos_v1:zombie_bruiser",
    "boh:gray_alien",
    "stalwart_dungeons:awful_ghast",
    "boh:deer",
    "born_in_chaos_v1:lord_the_headless",
    "call_of_yucutan:blowgun_huracan",
    "boh:torment_pyramid",
    "scguns:sky_carrier",
    "born_in_chaos_v1:diamond_termite",
    "cataclysm:kobolediator",
    "cataclysm:deepling_priest",
    "boh:unown_13",
    "vampirism:converted_mule",
    "boh:unown_12",
    "boh:unown_11",
    "minecraft:piglin",
    "boh:unown_10",
    "deeperdarker:shriek_worm",
    "boh:deer_mimic",
    "boh:unown_15",
    "boh:light_head",
    "boh:unown_14",
    "born_in_chaos_v1:sir_the_headless",
    "cataclysm:ignited_revenant",
    "graveyard:corrupted_vindicator",
    "boh:sadako",
    "minecraft:sniffer",
    "call_of_yucutan:ah_puch",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "cataclysm:royal_draugr",
    "zombies_plus:weak_zombie",
    "zombies_plus:sword_zombie",
    "born_in_chaos_v1:bonescaller",
    "theabyss:ice_skeleton",
    "deeperdarker:shattered",
    "boh:jason_mask",
    "theabyss:elder",
    "cataclysm:aptrgangr",
    "born_in_chaos_v1:missioner",
    "deeperdarker:sculk_snapper",
    "minecraft:ocelot",
    "cataclysm:modern_remnant",
    "fromtheshadows:bulldrogioth",
    "theabyss:summoned_seeker",
    "born_in_chaos_v1:supreme_bonescaller_not_despawn",
    "minecraft:wolf",
    "boh:gaster",
    "vampirism:dummy_creature"
]
